name: Manage Mutually Exclusive Labels

on:
  issues:
    types: [labeled]

jobs:
  manage_labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Grant write permission to issues

    steps:
      - name: Remove Mutually Exclusive Labels
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = ['step1', 'step2', 'step3']; // 互斥标签列表
            const labelToAdd = context.payload.label.name; // 获取添加的标签
            const issueNumber = context.issue.number; // 获取issue编号
            
            if lables.includes(lableToAdd) {
              // 遍历互斥标签
              for (const label of labels) {
                if (label !== labelToAdd) {
                  // 移除其他标签
                  await github.rest.issues.removeLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: issueNumber,
                    name: label
                  }).catch(err => console.log(`Could not remove label ${label}: ${err}`));
                }
              }
            }