name: Manage Mutual Labels

on:
  label:
    types: [created]

jobs:
  remove_other_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Remove other mutual labels
        uses: actions/github-script@v6
        with:
          script: |
            const { context, github } = require('@actions/github');
            const issue_number = context.issue.number;
            const newLabel = context.payload.label.name; // 获取新添加的标签
            const mutualLabels = ['step1', 'step2', 'step3']; // 定义互斥标签

            // 获取当前问题的标签
            const { data: issue } = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
            });

            // 移除互斥标签
            for (const label of mutualLabels) {
              if (label !== newLabel && issue.labels.some(l => l.name === label)) {
                await github.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue_number,
                  name: label,
                });
              }
            }